name: Python Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create releases, tags, and commit changes
      issues: write   # Needed for issues to be able to comment on them for the release
      pull-requests: write # Needed to update PRs with release information

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Crucial for semantic-release to analyze full commit history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install python-semantic-release

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # This makes sure the GITHUB_TOKEN is used for subsequent git operations
          # This is critical for pushing tags/commits back to the repo
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          
      - name: Run Semantic Release
        id: semantic
        uses: python-semantic-release/python-semantic-release@v10.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # use outputs from semantic-release (optional)
      - name: Echo new version (if released)
        if: steps.semantic.outputs.released == 'true'
        run: |
          echo "New version released: ${{ steps.semantic.outputs.version }}"
          echo "Release notes: ${{ steps.semantic.outputs.release_notes }}"
          echo "Release type: ${{ steps.semantic.outputs.release_type }}"
